language: python
services: postgresql
python:
  - "3.8"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER kamil WITH PASSWORD 'kamil';" -U postgres
script: python manage.py test